# Generated by Django 3.0.3 on 2020-02-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndelaEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'engineer',
            },
        ),
        migrations.CreateModel(
            name='PartnerEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eng.AndelaEngineer')),
            ],
            options={
                'db_table': 'partner',
            },
        ),
    ]
